// <auto-generated />
using System;
using GPMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPMS.Infrastructure.Migrations
{
    [DbContext(typeof(GpmsDbContext))]
    partial class GpmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPMS.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int>("ChecklistID")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ItemContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1m);

                    b.HasKey("ItemID");

                    b.HasIndex("ChecklistID");

                    b.ToTable("ChecklistItems", (string)null);

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            ChecklistID = 1,
                            ItemCode = "ARCH-01",
                            ItemContent = "Is the architecture solid?",
                            MaxScore = 5m,
                            OrderIndex = 1,
                            Weight = 50m
                        },
                        new
                        {
                            ItemID = 2,
                            ChecklistID = 1,
                            ItemCode = "CODE-01",
                            ItemContent = "Code quality for MVP",
                            MaxScore = 5m,
                            OrderIndex = 2,
                            Weight = 50m
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Evaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("ReviewRoundID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("EvaluationID");

                    b.HasIndex("GroupID");

                    b.HasIndex("ReviewerID");

                    b.HasIndex("ReviewRoundID", "ReviewerID", "GroupID")
                        .IsUnique();

                    b.ToTable("Evaluations", (string)null);

                    b.HasData(
                        new
                        {
                            EvaluationID = 1,
                            GroupID = 101,
                            ReviewRoundID = 1,
                            ReviewerID = "GV001",
                            Status = "Submitted",
                            SubmittedAt = new DateTime(2025, 3, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalScore = 8.5m
                        },
                        new
                        {
                            EvaluationID = 2,
                            GroupID = 100,
                            ReviewRoundID = 1,
                            ReviewerID = "GV002",
                            Status = "Submitted",
                            SubmittedAt = new DateTime(2025, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalScore = 7.0m
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.EvaluationDetail", b =>
                {
                    b.Property<int>("EvaluationID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("EvaluationID", "ItemID");

                    b.HasIndex("ItemID");

                    b.ToTable("EvaluationDetails", (string)null);

                    b.HasData(
                        new
                        {
                            EvaluationID = 1,
                            ItemID = 1,
                            Comment = "Solid microservices architecture",
                            Score = 4.5m
                        },
                        new
                        {
                            EvaluationID = 1,
                            ItemID = 2,
                            Comment = "Code is clean but lacks unit tests",
                            Score = 4.0m
                        },
                        new
                        {
                            EvaluationID = 2,
                            ItemID = 1,
                            Comment = "Architecture needs refinement",
                            Score = 3.5m
                        },
                        new
                        {
                            EvaluationID = 2,
                            ItemID = 2,
                            Comment = "Average code quality for this stage",
                            Score = 3.5m
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ExpertiseArea", b =>
                {
                    b.Property<int>("ExpertiseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertiseID"));

                    b.Property<string>("ExpertiseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MajorID")
                        .HasColumnType("int");

                    b.HasKey("ExpertiseID");

                    b.HasIndex("MajorID");

                    b.ToTable("ExpertiseAreas", (string)null);

                    b.HasData(
                        new
                        {
                            ExpertiseID = 1,
                            ExpertiseName = "Web Development",
                            MajorID = 1
                        },
                        new
                        {
                            ExpertiseID = 2,
                            ExpertiseName = "Mobile Development",
                            MajorID = 1
                        },
                        new
                        {
                            ExpertiseID = 3,
                            ExpertiseName = "AI/ML",
                            MajorID = 1
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Faculty", b =>
                {
                    b.Property<int>("FacultyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyID"));

                    b.Property<string>("FacultyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FacultyID");

                    b.HasIndex("FacultyCode")
                        .IsUnique();

                    b.ToTable("Faculties", (string)null);

                    b.HasData(
                        new
                        {
                            FacultyID = 1,
                            FacultyCode = "SE",
                            FacultyName = "Software Engineering Faculty"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EvaluationID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("EvaluationID")
                        .IsUnique();

                    b.ToTable("Feedbacks", (string)null);

                    b.HasData(
                        new
                        {
                            FeedbackID = 1,
                            Content = "Great architecture decisions. The code quality is above average but needs more inline comments and unit tests for the core business logic modules. Overall this is a solid submission.",
                            CreatedAt = new DateTime(2025, 3, 10, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            EvaluationID = 1
                        },
                        new
                        {
                            FeedbackID = 2,
                            Content = "The AI model design needs more justification. The architecture diagram is unclear for the traffic ingestion pipeline. Please revise the technical report with more detailed diagrams before the next round.",
                            CreatedAt = new DateTime(2025, 3, 12, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            EvaluationID = 2
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.FeedbackApproval", b =>
                {
                    b.Property<int>("FeedbackID")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AutoReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisibleToStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorID")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("FeedbackApprovals", (string)null);

                    b.HasData(
                        new
                        {
                            FeedbackID = 1,
                            ApprovalStatus = "Pending",
                            IsVisibleToStudent = false,
                            SupervisorComment = "",
                            SupervisorID = "GV002"
                        },
                        new
                        {
                            FeedbackID = 2,
                            ApprovalStatus = "Pending",
                            IsVisibleToStudent = false,
                            SupervisorComment = "",
                            SupervisorID = "GV001"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RoleInGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GroupID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("GroupMembers", (string)null);

                    b.HasData(
                        new
                        {
                            GroupID = 100,
                            UserID = "SE180001",
                            JoinedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(214),
                            RoleInGroup = "Leader"
                        },
                        new
                        {
                            GroupID = 100,
                            UserID = "SE180002",
                            JoinedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(216),
                            RoleInGroup = "Member"
                        },
                        new
                        {
                            GroupID = 101,
                            UserID = "SE180003",
                            JoinedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(217),
                            RoleInGroup = "Leader"
                        },
                        new
                        {
                            GroupID = 101,
                            UserID = "SE180004",
                            JoinedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(218),
                            RoleInGroup = "Member"
                        },
                        new
                        {
                            GroupID = 102,
                            UserID = "SE180005",
                            JoinedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(219),
                            RoleInGroup = "Leader"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.LecturerExpertise", b =>
                {
                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ExpertiseID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LecturerID", "ExpertiseID");

                    b.HasIndex("ExpertiseID");

                    b.ToTable("LecturerExpertise", (string)null);
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Major", b =>
                {
                    b.Property<int>("MajorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorID"));

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("MajorCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MajorID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("MajorCode")
                        .IsUnique();

                    b.ToTable("Majors", (string)null);

                    b.HasData(
                        new
                        {
                            MajorID = 1,
                            FacultyID = 1,
                            MajorCode = "SE",
                            MajorName = "Software Engineering"
                        },
                        new
                        {
                            MajorID = 2,
                            FacultyID = 1,
                            MajorCode = "SS",
                            MajorName = "Software Testing"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsEmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RelatedEntityID")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NotificationID");

                    b.HasIndex("RecipientID");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MajorID")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SemesterID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.HasKey("ProjectID");

                    b.HasIndex("MajorID");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.HasIndex("SemesterID");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectID = 100,
                            CreatedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(161),
                            MajorID = 1,
                            ProjectCode = "PRJ-01",
                            ProjectName = "AI Traffic Analyzer",
                            SemesterID = 1,
                            Status = "Active"
                        },
                        new
                        {
                            ProjectID = 101,
                            CreatedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(165),
                            MajorID = 1,
                            ProjectCode = "PRJ-02",
                            ProjectName = "Smart Healthcare System",
                            SemesterID = 1,
                            Status = "Active"
                        },
                        new
                        {
                            ProjectID = 102,
                            CreatedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(167),
                            MajorID = 1,
                            ProjectCode = "PRJ-03",
                            ProjectName = "E-Commerce Platform",
                            SemesterID = 1,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ProjectGroup", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("GroupID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectGroups", (string)null);

                    b.HasData(
                        new
                        {
                            GroupID = 100,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Group AI-01",
                            ProjectID = 100
                        },
                        new
                        {
                            GroupID = 101,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Group HC-01",
                            ProjectID = 101
                        },
                        new
                        {
                            GroupID = 102,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Group EC-01",
                            ProjectID = 102
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ProjectSupervisor", b =>
                {
                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProjectID", "LecturerID");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("LecturerID");

                    b.ToTable("ProjectSupervisors", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectID = 100,
                            LecturerID = "GV001",
                            AssignedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Main"
                        },
                        new
                        {
                            ProjectID = 101,
                            LecturerID = "GV002",
                            AssignedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Main"
                        },
                        new
                        {
                            ProjectID = 102,
                            LecturerID = "GV001",
                            AssignedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Main"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewChecklist", b =>
                {
                    b.Property<int>("ChecklistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewRoundID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ChecklistID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReviewRoundID")
                        .IsUnique();

                    b.ToTable("ReviewChecklists", (string)null);

                    b.HasData(
                        new
                        {
                            ChecklistID = 1,
                            CreatedAt = new DateTime(2026, 3, 14, 7, 36, 0, 876, DateTimeKind.Utc).AddTicks(305),
                            Description = "Evaluate early stage architecture",
                            ReviewRoundID = 1,
                            Title = "Cross Review 1 Checklist"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewRound", b =>
                {
                    b.Property<int>("ReviewRoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewRoundID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SemesterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Planned");

                    b.Property<DateTime>("SubmissionDeadline")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewRoundID");

                    b.HasIndex("SemesterID", "RoundNumber")
                        .IsUnique();

                    b.ToTable("ReviewRounds", (string)null);

                    b.HasData(
                        new
                        {
                            ReviewRoundID = 1,
                            EndDate = new DateTime(2026, 3, 24, 14, 36, 0, 876, DateTimeKind.Local).AddTicks(280),
                            RoundNumber = 1,
                            RoundType = "Online",
                            SemesterID = 1,
                            StartDate = new DateTime(2026, 3, 4, 14, 36, 0, 876, DateTimeKind.Local).AddTicks(267),
                            Status = "Ongoing",
                            SubmissionDeadline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ReviewRoundID = 2,
                            EndDate = new DateTime(2026, 4, 13, 14, 36, 0, 876, DateTimeKind.Local).AddTicks(282),
                            RoundNumber = 3,
                            RoundType = "Offline",
                            SemesterID = 1,
                            StartDate = new DateTime(2026, 4, 3, 14, 36, 0, 876, DateTimeKind.Local).AddTicks(282),
                            Status = "Planned",
                            SubmissionDeadline = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewSessionInfo", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("MeetLink")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewRoundID")
                        .HasColumnType("int");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionID");

                    b.HasIndex("GroupID");

                    b.HasIndex("RoomID");

                    b.HasIndex("ReviewRoundID", "GroupID")
                        .IsUnique();

                    b.ToTable("ReviewSessionInfo", (string)null);

                    b.HasData(
                        new
                        {
                            SessionID = 1,
                            GroupID = 101,
                            MeetLink = "https://meet.google.com/abc-defg-hij",
                            ReviewRoundID = 1,
                            RoomID = 1,
                            ScheduledAt = new DateTime(2025, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SessionID = 2,
                            GroupID = 100,
                            MeetLink = "https://meet.google.com/xyz-uvw-qrs",
                            ReviewRoundID = 1,
                            RoomID = 2,
                            ScheduledAt = new DateTime(2025, 3, 12, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SessionID = 3,
                            GroupID = 102,
                            MeetLink = "https://meet.google.com/pqr-stu-vwx",
                            ReviewRoundID = 1,
                            RoomID = 1,
                            ScheduledAt = new DateTime(2025, 3, 14, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewerAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRandom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ReviewRoundID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("GroupID");

                    b.HasIndex("ReviewerID");

                    b.HasIndex("ReviewRoundID", "GroupID", "ReviewerID")
                        .IsUnique();

                    b.ToTable("ReviewerAssignments", (string)null);

                    b.HasData(
                        new
                        {
                            AssignmentID = 1,
                            AssignedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupID = 101,
                            IsRandom = true,
                            ReviewRoundID = 1,
                            ReviewerID = "GV001"
                        },
                        new
                        {
                            AssignmentID = 2,
                            AssignedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupID = 100,
                            IsRandom = true,
                            ReviewRoundID = 1,
                            ReviewerID = "GV002"
                        },
                        new
                        {
                            AssignmentID = 3,
                            AssignedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupID = 102,
                            IsRandom = true,
                            ReviewRoundID = 2,
                            ReviewerID = "GV003"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<string>("Building")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Classroom");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.HasKey("RoomID");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            Building = "Alpha",
                            Capacity = 30,
                            RoomCode = "B1.01",
                            RoomType = "Classroom",
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 2,
                            Building = "Alpha",
                            Capacity = 30,
                            RoomCode = "B1.02",
                            RoomType = "Classroom",
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 3,
                            Building = "Delta",
                            Capacity = 100,
                            RoomCode = "Hall-A",
                            RoomType = "Hall",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Semester", b =>
                {
                    b.Property<int>("SemesterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterID"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SemesterCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Upcoming");

                    b.HasKey("SemesterID");

                    b.HasIndex("SemesterCode")
                        .IsUnique();

                    b.ToTable("Semesters", (string)null);

                    b.HasData(
                        new
                        {
                            SemesterID = 1,
                            AcademicYear = "2024-2025",
                            EndDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SemesterCode = "SP25",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Submission", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("FileSizeMB")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("RequirementID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("SubmissionID");

                    b.HasIndex("GroupID");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("RequirementID", "GroupID", "Version")
                        .IsUnique();

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("GPMS.Domain.Entities.SubmissionRequirement", b =>
                {
                    b.Property<int>("RequirementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementID"));

                    b.Property<string>("AllowedFormats")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxFileSizeMB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<int>("ReviewRoundID")
                        .HasColumnType("int");

                    b.HasKey("RequirementID");

                    b.HasIndex("ReviewRoundID");

                    b.ToTable("SubmissionRequirements", (string)null);
                });

            modelBuilder.Entity("GPMS.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_EmailOrUsername", "[Email] IS NOT NULL OR [Username] IS NOT NULL");
                        });

                    b.HasData(
                        new
                        {
                            UserID = "ADMIN001",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1803),
                            Email = "admin@fpt.edu.vn",
                            FullName = "System Admin",
                            Status = "Active",
                            Username = "admin"
                        },
                        new
                        {
                            UserID = "GV001",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1812),
                            Email = "giao-vien1@fpt.edu.vn",
                            FullName = "Lecturer One",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "GV002",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1814),
                            Email = "giao-vien2@fpt.edu.vn",
                            FullName = "Lecturer Two",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "GV003",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1816),
                            Email = "giao-vien3@fpt.edu.vn",
                            FullName = "Lecturer Three",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "HOD001",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1818),
                            Email = "hod@fpt.edu.vn",
                            FullName = "Head of Department",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "SE180001",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1819),
                            Email = "student1@fpt.edu.vn",
                            FullName = "Student One",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "SE180002",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1821),
                            Email = "student2@fpt.edu.vn",
                            FullName = "Student Two",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "SE180003",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1823),
                            Email = "student3@fpt.edu.vn",
                            FullName = "Student Three",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "SE180004",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1825),
                            Email = "student4@fpt.edu.vn",
                            FullName = "Student Four",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = "SE180005",
                            CreatedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1826),
                            Email = "student5@fpt.edu.vn",
                            FullName = "Student Five",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.UserCredential", b =>
                {
                    b.Property<int>("CredentialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialID"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExternalProviderID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CredentialID");

                    b.HasIndex("UserID", "AuthProvider")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("GPMS.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleID"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserRoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserRoleID = 1,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1852),
                            RoleName = "Admin",
                            UserID = "ADMIN001"
                        },
                        new
                        {
                            UserRoleID = 2,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1854),
                            RoleName = "Lecturer",
                            UserID = "GV001"
                        },
                        new
                        {
                            UserRoleID = 3,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1854),
                            RoleName = "Lecturer",
                            UserID = "GV002"
                        },
                        new
                        {
                            UserRoleID = 4,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1855),
                            RoleName = "Lecturer",
                            UserID = "GV003"
                        },
                        new
                        {
                            UserRoleID = 10,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1856),
                            RoleName = "HeadOfDept",
                            UserID = "HOD001"
                        },
                        new
                        {
                            UserRoleID = 5,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1856),
                            RoleName = "Student",
                            UserID = "SE180001"
                        },
                        new
                        {
                            UserRoleID = 6,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1857),
                            RoleName = "Student",
                            UserID = "SE180002"
                        },
                        new
                        {
                            UserRoleID = 7,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1858),
                            RoleName = "Student",
                            UserID = "SE180003"
                        },
                        new
                        {
                            UserRoleID = 8,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1859),
                            RoleName = "Student",
                            UserID = "SE180004"
                        },
                        new
                        {
                            UserRoleID = 9,
                            AssignedAt = new DateTime(2026, 3, 9, 8, 52, 25, 833, DateTimeKind.Utc).AddTicks(1859),
                            RoleName = "Student",
                            UserID = "SE180005"
                        });
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.ReviewChecklist", "Checklist")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ChecklistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.ProjectGroup", "Group")
                        .WithMany("Evaluations")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.ReviewRound", "ReviewRound")
                        .WithMany("Evaluations")
                        .HasForeignKey("ReviewRoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.User", "Reviewer")
                        .WithMany("Evaluations")
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("ReviewRound");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.EvaluationDetail", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("EvaluationDetails")
                        .HasForeignKey("EvaluationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.ChecklistItem", "Item")
                        .WithMany("EvaluationDetails")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ExpertiseArea", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Major", "Major")
                        .WithMany("ExpertiseAreas")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Major");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Evaluation", "Evaluation")
                        .WithOne("Feedback")
                        .HasForeignKey("GPMS.Domain.Entities.Feedback", "EvaluationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.FeedbackApproval", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Feedback", "Feedback")
                        .WithOne("FeedbackApproval")
                        .HasForeignKey("GPMS.Domain.Entities.FeedbackApproval", "FeedbackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.User", "Supervisor")
                        .WithMany("FeedbackApprovals")
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Feedback");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.ProjectGroup", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.LecturerExpertise", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.ExpertiseArea", "Expertise")
                        .WithMany("LecturerExpertises")
                        .HasForeignKey("ExpertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.User", "Lecturer")
                        .WithMany("LecturerExpertises")
                        .HasForeignKey("LecturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expertise");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Major", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Majors")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Notification", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Project", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Major", "Major")
                        .WithMany("Projects")
                        .HasForeignKey("MajorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.Semester", "Semester")
                        .WithMany("Projects")
                        .HasForeignKey("SemesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ProjectGroup", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Project", "Project")
                        .WithMany("ProjectGroups")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ProjectSupervisor", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.User", "AdminWhoAssigned")
                        .WithMany("ProjectsAssignedByMe")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GPMS.Domain.Entities.User", "Lecturer")
                        .WithMany("SupervisedProjects")
                        .HasForeignKey("LecturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.Project", "Project")
                        .WithMany("ProjectSupervisors")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminWhoAssigned");

                    b.Navigation("Lecturer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewChecklist", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.User", "Creator")
                        .WithMany("CreatedChecklists")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GPMS.Domain.Entities.ReviewRound", "ReviewRound")
                        .WithOne("ReviewChecklist")
                        .HasForeignKey("GPMS.Domain.Entities.ReviewChecklist", "ReviewRoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("ReviewRound");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewRound", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.Semester", "Semester")
                        .WithMany("ReviewRounds")
                        .HasForeignKey("SemesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewSessionInfo", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.ProjectGroup", "Group")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.ReviewRound", "ReviewRound")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("ReviewRoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.Room", "Room")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("ReviewRound");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewerAssignment", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.User", "AdminWhoAssigned")
                        .WithMany("ReviewersAssignedByMe")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GPMS.Domain.Entities.ProjectGroup", "Group")
                        .WithMany("ReviewerAssignments")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.ReviewRound", "ReviewRound")
                        .WithMany("ReviewerAssignments")
                        .HasForeignKey("ReviewRoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.User", "Reviewer")
                        .WithMany("ReviewerAssignments")
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminWhoAssigned");

                    b.Navigation("Group");

                    b.Navigation("ReviewRound");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Submission", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.ProjectGroup", "Group")
                        .WithMany("Submissions")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.SubmissionRequirement", "Requirement")
                        .WithMany("Submissions")
                        .HasForeignKey("RequirementID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Domain.Entities.User", "Submitter")
                        .WithMany("Submissions")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Requirement");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.SubmissionRequirement", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.ReviewRound", "ReviewRound")
                        .WithMany("SubmissionRequirements")
                        .HasForeignKey("ReviewRoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewRound");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.UserCredential", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.User", "User")
                        .WithMany("UserCredentials")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("GPMS.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ChecklistItem", b =>
                {
                    b.Navigation("EvaluationDetails");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Evaluation", b =>
                {
                    b.Navigation("EvaluationDetails");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ExpertiseArea", b =>
                {
                    b.Navigation("LecturerExpertises");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Feedback", b =>
                {
                    b.Navigation("FeedbackApproval");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Major", b =>
                {
                    b.Navigation("ExpertiseAreas");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectGroups");

                    b.Navigation("ProjectSupervisors");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ProjectGroup", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("GroupMembers");

                    b.Navigation("ReviewSessions");

                    b.Navigation("ReviewerAssignments");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewChecklist", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.ReviewRound", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("ReviewChecklist");

                    b.Navigation("ReviewSessions");

                    b.Navigation("ReviewerAssignments");

                    b.Navigation("SubmissionRequirements");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Room", b =>
                {
                    b.Navigation("ReviewSessions");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("ReviewRounds");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.SubmissionRequirement", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GPMS.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedChecklists");

                    b.Navigation("Evaluations");

                    b.Navigation("FeedbackApprovals");

                    b.Navigation("GroupMemberships");

                    b.Navigation("LecturerExpertises");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectsAssignedByMe");

                    b.Navigation("ReviewerAssignments");

                    b.Navigation("ReviewersAssignedByMe");

                    b.Navigation("Submissions");

                    b.Navigation("SupervisedProjects");

                    b.Navigation("UserCredentials");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
